import type { Locale } from "@/lib/i18n";

export const inquiryCopy: Record<Locale, Record<string, string>> = {
  en: { eyebrow: "CORPORATE ACCOMMODATION DESK", title: "Share your group accommodation requirements.", body: "Provide your travel brief and our accommodation desk will review the group size, dates, preferred location, rooming requirements, and operational notes before responding through your preferred contact channel.", companyName: "Company name", contactName: "Primary contact", email: "Business email", phone: "Telephone or WhatsApp", country: "Country of organisation", city: "Preferred city", rooms: "Rooms required", guests: "Number of guests", checkIn: "Proposed check-in", checkOut: "Proposed check-out", duration: "Long-stay requirement", durationPlaceholder: "e.g. 30 nights", hotels: "Preferred property or requirements", notes: "Additional operational notes", submit: "Submit accommodation enquiry", sending: "Submitting enquiry…", success: "Your accommodation enquiry has been received. Our team will respond using your preferred contact details.", error: "We could not submit your enquiry. Please contact our accommodation desk by WhatsApp or email.", direct: "Prefer to speak with our accommodation desk?", call: "Call +966 56 375 6320", whatsapp: "WhatsApp — Saudi Arabia", whatsapp2: "WhatsApp", emailAction: "Email our accommodation desk", optional: "Optional", cityMadinah: "Madinah Al Munawwarah", cityMakkah: "Makkah Al Mukarramah" },
  ar: { eyebrow: "مكتب إقامة الشركات", title: "شاركنا متطلبات إقامة مجموعتك.", body: "أرسل موجز السفر ليراجع فريق الإقامة حجم المجموعة والتواريخ والموقع المفضل ومتطلبات الغرف والملاحظات التشغيلية، ثم يتواصل معك عبر وسيلة الاتصال التي تفضلها.", companyName: "اسم الشركة", contactName: "جهة الاتصال الرئيسية", email: "البريد الإلكتروني للعمل", phone: "الهاتف أو واتساب", country: "دولة الجهة", city: "المدينة المفضلة", rooms: "عدد الغرف المطلوبة", guests: "عدد الضيوف", checkIn: "تاريخ الوصول المقترح", checkOut: "تاريخ المغادرة المقترح", duration: "متطلبات الإقامة الطويلة", durationPlaceholder: "مثال: 30 ليلة", hotels: "المنشأة المفضلة أو المتطلبات", notes: "ملاحظات تشغيلية إضافية", submit: "إرسال طلب الإقامة", sending: "جارٍ إرسال الطلب…", success: "تم استلام طلب الإقامة. سيتواصل فريقنا عبر بيانات الاتصال التي قدمتها.", error: "تعذر إرسال طلبك. يرجى التواصل مع مكتب الإقامة عبر واتساب أو البريد الإلكتروني.", direct: "تفضل التحدث مع مكتب الإقامة؟", call: "اتصل +966 56 375 6320", whatsapp: "واتساب — السعودية", whatsapp2: "واتساب", emailAction: "راسل مكتب الإقامة", optional: "اختياري", cityMadinah: "المدينة المنورة", cityMakkah: "مكة المكرمة" },
  ms: { eyebrow: "MEJA PENGINAPAN KORPORAT", title: "Kongsikan keperluan penginapan kumpulan anda.", body: "Berikan ringkasan perjalanan supaya meja penginapan kami dapat menilai saiz kumpulan, tarikh, lokasi pilihan, keperluan bilik dan maklumat operasi sebelum menghubungi anda melalui saluran pilihan anda.", companyName: "Nama syarikat", contactName: "Pegawai perhubungan utama", email: "E-mel perniagaan", phone: "Telefon atau WhatsApp", country: "Negara organisasi", city: "Bandar pilihan", rooms: "Bilik diperlukan", guests: "Bilangan tetamu", checkIn: "Daftar masuk dicadangkan", checkOut: "Daftar keluar dicadangkan", duration: "Keperluan penginapan panjang", durationPlaceholder: "cth. 30 malam", hotels: "Hotel pilihan atau keperluan", notes: "Nota operasi tambahan", submit: "Hantar pertanyaan penginapan", sending: "Menghantar pertanyaan…", success: "Pertanyaan penginapan anda telah diterima. Pasukan kami akan menghubungi anda melalui butiran hubungan yang diberikan.", error: "Kami tidak dapat menghantar pertanyaan anda. Sila hubungi meja penginapan kami melalui WhatsApp atau e-mel.", direct: "Lebih suka berbincang dengan meja penginapan kami?", call: "Telefon +966 56 375 6320", whatsapp: "WhatsApp — Arab Saudi", whatsapp2: "WhatsApp", emailAction: "E-mel meja penginapan", optional: "Pilihan", cityMadinah: "Madinah Al Munawwarah", cityMakkah: "Makkah Al Mukarramah" },
  ur: { eyebrow: "کارپوریٹ رہائش ڈیسک", title: "اپنی گروپ رہائش کی ضروریات سے آگاہ کریں۔", body: "اپنا سفری بریف فراہم کریں تاکہ ہمارا رہائشی ڈیسک گروپ کے سائز، تاریخوں، پسندیدہ مقام، رومنگ ضروریات اور آپریشنل نوٹس کا جائزہ لے کر آپ کے پسندیدہ رابطے کے ذریعے جواب دے سکے۔", companyName: "کمپنی کا نام", contactName: "بنیادی رابطہ", email: "کاروباری ای میل", phone: "فون یا واٹس ایپ", country: "ادارے کا ملک", city: "پسندیدہ شہر", rooms: "درکار کمرے", guests: "مہمانوں کی تعداد", checkIn: "مجوزہ چیک اِن", checkOut: "مجوزہ چیک آؤٹ", duration: "طویل قیام کی ضرورت", durationPlaceholder: "مثال: 30 راتیں", hotels: "پسندیدہ ہوٹل یا تقاضے", notes: "اضافی آپریشنل نوٹس", submit: "رہائش انکوائری بھیجیں", sending: "انکوائری بھیجی جا رہی ہے…", success: "آپ کی رہائش انکوائری موصول ہوگئی ہے۔ ہماری ٹیم آپ کی فراہم کردہ رابطہ تفصیلات کے ذریعے جواب دے گی۔", error: "آپ کی انکوائری جمع نہیں ہوسکی۔ براہ کرم واٹس ایپ یا ای میل کے ذریعے ہمارے رہائشی ڈیسک سے رابطہ کریں۔", direct: "ہمارے رہائشی ڈیسک سے بات کرنا پسند کریں گے؟", call: "کال +966 56 375 6320", whatsapp: "واٹس ایپ — سعودی عرب", whatsapp2: "واٹس ایپ", emailAction: "رہائشی ڈیسک کو ای میل کریں", optional: "اختیاری", cityMadinah: "مدینہ منورہ", cityMakkah: "مکہ مکرمہ" },
  id: { eyebrow: "MEJA AKOMODASI KORPORAT", title: "Sampaikan kebutuhan akomodasi grup Anda.", body: "Bagikan ringkasan perjalanan agar meja akomodasi kami dapat meninjau ukuran grup, tanggal, lokasi pilihan, kebutuhan kamar, dan catatan operasional sebelum menanggapi melalui saluran kontak pilihan Anda.", companyName: "Nama perusahaan", contactName: "Kontak utama", email: "Email bisnis", phone: "Telepon atau WhatsApp", country: "Negara organisasi", city: "Kota pilihan", rooms: "Kamar yang diperlukan", guests: "Jumlah tamu", checkIn: "Rencana check-in", checkOut: "Rencana check-out", duration: "Kebutuhan masa tinggal panjang", durationPlaceholder: "mis. 30 malam", hotels: "Hotel pilihan atau kebutuhan", notes: "Catatan operasional tambahan", submit: "Kirim pertanyaan akomodasi", sending: "Mengirim pertanyaan…", success: "Pertanyaan akomodasi Anda telah diterima. Tim kami akan menanggapi melalui detail kontak yang Anda berikan.", error: "Kami tidak dapat mengirim pertanyaan Anda. Silakan hubungi meja akomodasi kami melalui WhatsApp atau email.", direct: "Ingin berbicara dengan meja akomodasi kami?", call: "Telepon +966 56 375 6320", whatsapp: "WhatsApp — Arab Saudi", whatsapp2: "WhatsApp", emailAction: "Email meja akomodasi", optional: "Opsional", cityMadinah: "Madinah Al Munawwarah", cityMakkah: "Makkah Al Mukarramah" },
  hi: { eyebrow: "कॉर्पोरेट आवास डेस्क", title: "अपनी समूह आवास आवश्यकताएं साझा करें।", body: "अपना यात्रा विवरण दें ताकि हमारा आवास डेस्क समूह आकार, तिथियों, पसंदीदा स्थान, कक्ष आवश्यकताओं और परिचालन नोट्स की समीक्षा कर आपके पसंदीदा संपर्क माध्यम से उत्तर दे सके।", companyName: "कंपनी का नाम", contactName: "मुख्य संपर्क", email: "व्यावसायिक ईमेल", phone: "टेलीफोन या व्हाट्सऐप", country: "संस्था का देश", city: "पसंदीदा शहर", rooms: "आवश्यक कमरे", guests: "अतिथियों की संख्या", checkIn: "प्रस्तावित चेक-इन", checkOut: "प्रस्तावित चेक-आउट", duration: "दीर्घकालिक ठहराव की आवश्यकता", durationPlaceholder: "उदा. 30 रातें", hotels: "पसंदीदा होटल या आवश्यकताएं", notes: "अतिरिक्त परिचालन नोट्स", submit: "आवास अनुरोध भेजें", sending: "अनुरोध भेजा जा रहा है…", success: "आपका आवास अनुरोध प्राप्त हो गया है। हमारी टीम आपके दिए गए संपर्क विवरण के माध्यम से उत्तर देगी।", error: "हम आपका अनुरोध नहीं भेज सके। कृपया हमारे आवास डेस्क से व्हाट्सऐप या ईमेल द्वारा संपर्क करें।", direct: "हमारे आवास डेस्क से बात करना पसंद करेंगे?", call: "कॉल +966 56 375 6320", whatsapp: "व्हाट्सऐप — सऊदी अरब", whatsapp2: "व्हाट्सऐप", emailAction: "आवास डेस्क को ईमेल करें", optional: "वैकल्पिक", cityMadinah: "मदीना अल मुनव्वरा", cityMakkah: "मक्का अल मुकर्रमा" },
};

const directChannelCopy: Record<Locale, string> = {
  en: "Prefer WhatsApp or email?",
  ar: "تفضلون واتساب أو البريد الإلكتروني؟",
  ms: "Lebih selesa melalui WhatsApp atau e-mel?",
  ur: "واٹس ایپ یا ای میل کو ترجیح دیتے ہیں؟",
  id: "Lebih memilih WhatsApp atau email?",
  hi: "व्हाट्सऐप या ईमेल पसंद करेंगे?",
};

for (const locale of Object.keys(inquiryCopy) as Locale[]) {
  delete inquiryCopy[locale].call;
  inquiryCopy[locale].direct = directChannelCopy[locale];
  inquiryCopy[locale].whatsapp = inquiryCopy[locale].whatsapp2;
}
