import type { Locale } from "@/lib/i18n";
import type { MadinahDirectoryZone } from "@shared/madinahPlanning";

type PlanningCopy = {
  planning: string;
  source: string;
  distance: string;
  walking: string;
  vehicle: string;
  liveRoute: string;
  noMedia: string;
  noDetails: string;
  noRoute: string;
  gatePending: string;
  access: Record<"walkable" | "transfer_advised", string>;
  zones: Record<MadinahDirectoryZone, string>;
  summary: (name: string) => string;
};

export const planningCopy: Record<Locale, PlanningCopy> = {
  en: { planning: "ACCOMMODATION OPTION", source: "ACCOMMODATION DETAILS", distance: "Location", walking: "Access", vehicle: "Transfer", liveRoute: "Walking route", noMedia: "Hotel imagery will be added as it becomes available.", noDetails: "Share your group dates and requirements, and our accommodation team will prepare the suitable options for your programme.", noRoute: "Location details can be shared by our accommodation team according to your group’s requirements.", gatePending: "Our team can advise on the most suitable arrival and access arrangements for your group.", access: { walkable: "Central Madinah access", transfer_advised: "Transfer arrangements available" }, zones: { central_north: "Central Area — North", central_east: "Central Area — East", central_south: "Central Area — South", central_west: "Central Area — West", northern_transfer: "North Madinah / King Fahad Road", other_districts: "Madinah districts" }, summary: name => `${name} is an accommodation option in Madinah. Share your group dates and requirements, and our team will help you choose the arrangement that suits your programme.` },
  ar: { planning: "خيار إقامة", source: "تفاصيل الإقامة", distance: "الموقع", walking: "الوصول", vehicle: "النقل", liveRoute: "مسار المشي", noMedia: "تُضاف صور الفندق عند توفرها.", noDetails: "شاركوا معنا تواريخ مجموعتكم ومتطلباتها، وسنرتب لكم خيارات الإقامة المناسبة لبرنامجكم.", noRoute: "يشارككم فريق الإقامة تفاصيل الموقع بما يناسب متطلبات مجموعتكم.", gatePending: "يساعدكم فريقنا في اختيار ترتيبات الوصول الأنسب لمجموعتكم.", access: { walkable: "موقع في المدينة المنورة", transfer_advised: "ترتيبات نقل متاحة" }, zones: { central_north: "المنطقة المركزية — شمال", central_east: "المنطقة المركزية — شرق", central_south: "المنطقة المركزية — جنوب", central_west: "المنطقة المركزية — غرب", northern_transfer: "شمال المدينة المنورة / طريق الملك فهد", other_districts: "أحياء المدينة المنورة" }, summary: name => `${name} خيار إقامة في المدينة المنورة. شاركوا معنا تواريخ مجموعتكم ومتطلباتها، وسنساعدكم على اختيار الترتيب الذي يناسب برنامجكم.` },
  ms: { planning: "PILIHAN PENGINAPAN", source: "BUTIRAN PENGINAPAN", distance: "Lokasi", walking: "Akses", vehicle: "Pemindahan", liveRoute: "Laluan berjalan", noMedia: "Imej hotel akan ditambah apabila tersedia.", noDetails: "Kongsikan tarikh dan keperluan kumpulan anda, dan pasukan kami akan menyediakan pilihan yang sesuai untuk program anda.", noRoute: "Butiran lokasi boleh dikongsi oleh pasukan penginapan kami mengikut keperluan kumpulan anda.", gatePending: "Pasukan kami boleh membantu mengatur ketibaan dan akses yang sesuai untuk kumpulan anda.", access: { walkable: "Akses Madinah pusat", transfer_advised: "Susunan pemindahan tersedia" }, zones: { central_north: "Kawasan Pusat — Utara", central_east: "Kawasan Pusat — Timur", central_south: "Kawasan Pusat — Selatan", central_west: "Kawasan Pusat — Barat", northern_transfer: "Madinah Utara / Jalan King Fahad", other_districts: "Daerah Madinah" }, summary: name => `${name} ialah pilihan penginapan di Madinah. Kongsikan tarikh dan keperluan kumpulan anda, dan pasukan kami akan membantu memilih susunan yang sesuai untuk program anda.` },
  ur: { planning: "رہائش کا انتخاب", source: "رہائش کی تفصیلات", distance: "مقام", walking: "رسائی", vehicle: "منتقلی", liveRoute: "پیدل راستہ", noMedia: "ہوٹل کی تصاویر دستیاب ہونے پر شامل کی جائیں گی۔", noDetails: "اپنے گروپ کی تاریخیں اور ضروریات بتائیں، اور ہماری رہائش ٹیم آپ کے پروگرام کے لیے موزوں اختیارات ترتیب دے گی۔", noRoute: "مقام کی تفصیلات ہماری رہائش ٹیم آپ کے گروپ کی ضروریات کے مطابق فراہم کرسکتی ہے۔", gatePending: "ہماری ٹیم آپ کے گروپ کے لیے موزوں آمد اور رسائی کے انتظامات میں مدد کرسکتی ہے۔", access: { walkable: "مرکزی مدینہ رسائی", transfer_advised: "منتقلی کے انتظامات دستیاب" }, zones: { central_north: "مرکزی علاقہ — شمال", central_east: "مرکزی علاقہ — مشرق", central_south: "مرکزی علاقہ — جنوب", central_west: "مرکزی علاقہ — مغرب", northern_transfer: "شمالی مدینہ / کنگ فہد روڈ", other_districts: "مدینہ کے اضلاع" }, summary: name => `${name} مدینہ میں رہائش کا ایک انتخاب ہے۔ اپنے گروپ کی تاریخیں اور ضروریات بتائیں، اور ہماری ٹیم آپ کے پروگرام کے لیے موزوں ترتیب منتخب کرنے میں مدد کرے گی۔` },
  id: { planning: "PILIHAN AKOMODASI", source: "DETAIL AKOMODASI", distance: "Lokasi", walking: "Akses", vehicle: "Transfer", liveRoute: "Rute berjalan", noMedia: "Gambar hotel akan ditambahkan saat tersedia.", noDetails: "Bagikan tanggal dan kebutuhan grup Anda, dan tim kami akan menyiapkan pilihan yang sesuai untuk program Anda.", noRoute: "Rincian lokasi dapat dibagikan oleh tim akomodasi kami sesuai kebutuhan grup Anda.", gatePending: "Tim kami dapat membantu mengatur kedatangan dan akses yang sesuai untuk grup Anda.", access: { walkable: "Akses Madinah pusat", transfer_advised: "Pengaturan transfer tersedia" }, zones: { central_north: "Area Pusat — Utara", central_east: "Area Pusat — Timur", central_south: "Area Pusat — Selatan", central_west: "Area Pusat — Barat", northern_transfer: "Madinah Utara / Jalan King Fahad", other_districts: "Distrik Madinah" }, summary: name => `${name} adalah pilihan akomodasi di Madinah. Bagikan tanggal dan kebutuhan grup Anda, dan tim kami akan membantu memilih pengaturan yang sesuai untuk program Anda.` },
  hi: { planning: "आवास विकल्प", source: "आवास विवरण", distance: "स्थान", walking: "पहुंच", vehicle: "स्थानांतरण", liveRoute: "पैदल मार्ग", noMedia: "होटल की छवियां उपलब्ध होने पर जोड़ी जाएंगी।", noDetails: "अपने समूह की तिथियां और आवश्यकताएं साझा करें, और हमारी आवास टीम आपके कार्यक्रम के लिए उपयुक्त विकल्प तैयार करेगी।", noRoute: "स्थान विवरण हमारी आवास टीम आपके समूह की आवश्यकताओं के अनुसार साझा कर सकती है।", gatePending: "हमारी टीम आपके समूह के लिए उपयुक्त आगमन और पहुंच व्यवस्था में सहायता कर सकती है।", access: { walkable: "केंद्रीय मदीना पहुंच", transfer_advised: "स्थानांतरण व्यवस्था उपलब्ध" }, zones: { central_north: "केंद्रीय क्षेत्र — उत्तर", central_east: "केंद्रीय क्षेत्र — पूर्व", central_south: "केंद्रीय क्षेत्र — दक्षिण", central_west: "केंद्रीय क्षेत्र — पश्चिम", northern_transfer: "उत्तरी मदीना / किंग फहद रोड", other_districts: "मदीना के क्षेत्र" }, summary: name => `${name} मदीना में एक आवास विकल्प है। अपने समूह की तिथियां और आवश्यकताएं साझा करें, और हमारी टीम आपके कार्यक्रम के लिए उपयुक्त व्यवस्था चुनने में सहायता करेगी।` },
};
