import type { Locale } from "./i18n";

type ReviewCopy = {
  eyebrow: string; title: string; body: string; trust: string; approvedTitle: string; approvedBody: string; approvedEmpty: string;
  formTitle: string; formBody: string; companyName: string; contactName: string; email: string; phone: string; serviceType: string;
  servicePlaceholder: string; rating: string; reviewBody: string; reviewPlaceholder: string; experienceConfirmed: string; publishConsent: string;
  displayCompanyName: string; submit: string; sending: string; success: string; error: string; ratingError: string; anonymousCompany: string; footerAction: string;
};

export const reviewCopy: Record<Locale, ReviewCopy> = {
  en: {
    eyebrow: "PARTNER FEEDBACK", title: "Share your experience with Al Ghanem Travel.", body: "Your feedback helps us serve travel companies and their guests with greater care, clarity, and consistency.", trust: "We publish only genuine feedback that has been reviewed by our team and submitted with permission to publish.", approvedTitle: "Approved partner feedback", approvedBody: "Comments below are published only after moderation. Company names appear only where the respondent permitted this.", approvedEmpty: "Approved feedback will appear here once a partner has chosen to share it publicly.", formTitle: "Send feedback for review", formBody: "Please share feedback based on a completed experience with Al Ghanem Travel. Your submission is not published automatically.", companyName: "Company name", contactName: "Primary contact", email: "Business email", phone: "Telephone or WhatsApp", serviceType: "Service received", servicePlaceholder: "Select or describe the service", rating: "Overall rating", reviewBody: "Your feedback", reviewPlaceholder: "Tell us what worked well and what we can improve.", experienceConfirmed: "I confirm this feedback is based on a genuine experience with Al Ghanem Travel.", publishConsent: "I allow Al Ghanem Travel to review this feedback for possible public publication.", displayCompanyName: "You may display my company name if this feedback is approved.", submit: "Send feedback for review", sending: "Sending feedback…", success: "Thank you. Your feedback has been received and will be reviewed before any publication.", error: "We could not send your feedback. Please try again or contact Al Ghanem Travel directly.", ratingError: "Please select an overall rating before sending your feedback.", anonymousCompany: "Verified partner", footerAction: "Share your experience",
  },
  ar: {
    eyebrow: "آراء الشركاء", title: "شاركوا تجربتكم مع الغانم ترافل.", body: "تساعدنا آراؤكم على خدمة شركات السفر وضيوفهم بعناية أكبر ووضوح ثابت.", trust: "ننشر فقط الآراء الحقيقية التي يراجعها فريقنا ويوافق أصحابها على نشرها.", approvedTitle: "آراء الشركات وعملائنا", approvedBody: "لا يظهر أي رأي هنا إلا بعد المراجعة. ويظهر اسم الشركة فقط عند موافقة صاحب الرأي على ذلك.", approvedEmpty: "ستظهر الآراء المعتمدة هنا عندما يختار أحد الشركاء مشاركتها علناً.", formTitle: "أرسلوا رأيكم للمراجعة", formBody: "يرجى مشاركة رأي يستند إلى تجربة فعلية مع الغانم ترافل. لا يُنشر أي رأي تلقائياً.", companyName: "اسم الشركة", contactName: "مسؤول التواصل الرئيسي", email: "البريد الإلكتروني للعمل", phone: "رقم الهاتف أو واتساب", serviceType: "الخدمة التي تلقيتموها", servicePlaceholder: "اختاروا أو اكتبوا نوع الخدمة", rating: "التقييم العام", reviewBody: "رأيكم", reviewPlaceholder: "أخبرونا بما كان جيداً وما يمكننا تحسينه.", experienceConfirmed: "أؤكد أن هذا الرأي يستند إلى تجربة فعلية مع الغانم ترافل.", publishConsent: "أوافق على أن تراجع الغانم ترافل هذا الرأي للنظر في نشره علناً.", displayCompanyName: "يمكنكم إظهار اسم شركتي إذا تمت الموافقة على هذا الرأي.", submit: "إرسال الرأي للمراجعة", sending: "جارٍ إرسال الرأي…", success: "شكراً لكم. تم استلام رأيكم وسيتم مراجعته قبل أي نشر.", error: "تعذر إرسال رأيكم الآن. يرجى المحاولة مرة أخرى أو التواصل مباشرة مع الغانم ترافل.", ratingError: "يرجى اختيار التقييم العام قبل إرسال رأيكم.", anonymousCompany: "شريك تمت مراجعته", footerAction: "شاركوا تجربتكم",
  },
  ms: {
    eyebrow: "MAKLUM BALAS RAKAN KONGSI", title: "Kongsikan pengalaman anda bersama Al Ghanem Travel.", body: "Maklum balas anda membantu kami melayani syarikat perjalanan dan tetamu mereka dengan lebih teliti dan konsisten.", trust: "Kami hanya menerbitkan maklum balas tulen yang disemak oleh pasukan kami dan mendapat kebenaran untuk diterbitkan.", approvedTitle: "Maklum balas rakan kongsi yang diluluskan", approvedBody: "Setiap komen disiarkan hanya selepas semakan. Nama syarikat dipaparkan hanya dengan kebenaran responden.", approvedEmpty: "Maklum balas yang diluluskan akan muncul di sini apabila rakan kongsi memilih untuk berkongsinya secara terbuka.", formTitle: "Hantar maklum balas untuk semakan", formBody: "Sila kongsi maklum balas berdasarkan pengalaman sebenar bersama Al Ghanem Travel. Penghantaran anda tidak diterbitkan secara automatik.", companyName: "Nama syarikat", contactName: "Pegawai perhubungan utama", email: "E-mel perniagaan", phone: "Telefon atau WhatsApp", serviceType: "Perkhidmatan diterima", servicePlaceholder: "Pilih atau nyatakan perkhidmatan", rating: "Penilaian keseluruhan", reviewBody: "Maklum balas anda", reviewPlaceholder: "Kongsikan perkara yang berjalan baik dan yang boleh kami perbaiki.", experienceConfirmed: "Saya mengesahkan maklum balas ini berdasarkan pengalaman sebenar bersama Al Ghanem Travel.", publishConsent: "Saya membenarkan Al Ghanem Travel menyemak maklum balas ini untuk kemungkinan penerbitan awam.", displayCompanyName: "Anda boleh memaparkan nama syarikat saya jika maklum balas ini diluluskan.", submit: "Hantar untuk semakan", sending: "Menghantar maklum balas…", success: "Terima kasih. Maklum balas anda diterima dan akan disemak sebelum diterbitkan.", error: "Kami tidak dapat menghantar maklum balas anda. Sila cuba lagi atau hubungi Al Ghanem Travel terus.", ratingError: "Sila pilih penilaian keseluruhan sebelum menghantar maklum balas.", anonymousCompany: "Rakan kongsi disahkan", footerAction: "Kongsi pengalaman anda",
  },
  ur: {
    eyebrow: "پارٹنر فیڈ بیک", title: "Al Ghanem Travel کے ساتھ اپنا تجربہ شیئر کریں۔", body: "آپ کا فیڈ بیک ہمیں سفری کمپنیوں اور ان کے مہمانوں کی زیادہ توجہ اور وضاحت کے ساتھ خدمت کرنے میں مدد دیتا ہے۔", trust: "ہم صرف حقیقی فیڈ بیک شائع کرتے ہیں جسے ہماری ٹیم نے دیکھا ہو اور جس کے لیے اشاعت کی اجازت دی گئی ہو۔", approvedTitle: "منظور شدہ پارٹنر فیڈ بیک", approvedBody: "ہر تبصرہ صرف جائزے کے بعد شائع ہوتا ہے۔ کمپنی کا نام صرف جواب دہندہ کی اجازت سے ظاہر ہوتا ہے۔", approvedEmpty: "منظور شدہ فیڈ بیک یہاں اس وقت ظاہر ہوگا جب کوئی پارٹنر اسے عوامی طور پر شیئر کرنے کا انتخاب کرے۔", formTitle: "فیڈ بیک جائزے کے لیے بھیجیں", formBody: "براہ کرم Al Ghanem Travel کے ساتھ حقیقی تجربے کی بنیاد پر فیڈ بیک شیئر کریں۔ آپ کی جمع کرائی ہوئی رائے خودکار طور پر شائع نہیں ہوگی۔", companyName: "کمپنی کا نام", contactName: "بنیادی رابطہ", email: "کاروباری ای میل", phone: "فون یا واٹس ایپ", serviceType: "موصولہ خدمت", servicePlaceholder: "خدمت منتخب یا بیان کریں", rating: "مجموعی درجہ بندی", reviewBody: "آپ کا فیڈ بیک", reviewPlaceholder: "بتائیں کہ کیا اچھا رہا اور ہم کیا بہتر کر سکتے ہیں۔", experienceConfirmed: "میں تصدیق کرتا ہوں کہ یہ فیڈ بیک Al Ghanem Travel کے ساتھ حقیقی تجربے پر مبنی ہے۔", publishConsent: "میں Al Ghanem Travel کو اس فیڈ بیک کے عوامی اشاعت کے لیے جائزے کی اجازت دیتا ہوں۔", displayCompanyName: "اگر یہ فیڈ بیک منظور ہو تو آپ میری کمپنی کا نام ظاہر کر سکتے ہیں۔", submit: "جائزے کے لیے بھیجیں", sending: "فیڈ بیک بھیجا جا رہا ہے…", success: "شکریہ۔ آپ کا فیڈ بیک موصول ہوگیا ہے اور اشاعت سے پہلے اس کا جائزہ لیا جائے گا۔", error: "آپ کا فیڈ بیک نہیں بھیجا جا سکا۔ دوبارہ کوشش کریں یا براہ راست Al Ghanem Travel سے رابطہ کریں۔", ratingError: "فیڈ بیک بھیجنے سے پہلے مجموعی درجہ بندی منتخب کریں۔", anonymousCompany: "تصدیق شدہ پارٹنر", footerAction: "اپنا تجربہ شیئر کریں",
  },
  id: {
    eyebrow: "MASUKAN MITRA", title: "Bagikan pengalaman Anda bersama Al Ghanem Travel.", body: "Masukan Anda membantu kami melayani perusahaan perjalanan dan tamu mereka dengan perhatian dan kejelasan yang lebih baik.", trust: "Kami hanya menerbitkan masukan asli yang telah ditinjau tim kami dan diberi izin untuk dipublikasikan.", approvedTitle: "Masukan mitra yang disetujui", approvedBody: "Setiap komentar hanya diterbitkan setelah moderasi. Nama perusahaan ditampilkan hanya atas izin responden.", approvedEmpty: "Masukan yang disetujui akan tampil di sini ketika mitra memilih untuk membagikannya secara publik.", formTitle: "Kirim masukan untuk ditinjau", formBody: "Silakan bagikan masukan berdasarkan pengalaman nyata bersama Al Ghanem Travel. Kiriman Anda tidak diterbitkan secara otomatis.", companyName: "Nama perusahaan", contactName: "Kontak utama", email: "Email bisnis", phone: "Telepon atau WhatsApp", serviceType: "Layanan yang diterima", servicePlaceholder: "Pilih atau jelaskan layanan", rating: "Penilaian keseluruhan", reviewBody: "Masukan Anda", reviewPlaceholder: "Ceritakan yang berjalan baik dan yang dapat kami tingkatkan.", experienceConfirmed: "Saya mengonfirmasi bahwa masukan ini berdasarkan pengalaman nyata bersama Al Ghanem Travel.", publishConsent: "Saya mengizinkan Al Ghanem Travel meninjau masukan ini untuk kemungkinan publikasi.", displayCompanyName: "Anda dapat menampilkan nama perusahaan saya jika masukan ini disetujui.", submit: "Kirim untuk ditinjau", sending: "Mengirim masukan…", success: "Terima kasih. Masukan Anda telah diterima dan akan ditinjau sebelum dipublikasikan.", error: "Kami tidak dapat mengirim masukan Anda. Silakan coba lagi atau hubungi Al Ghanem Travel langsung.", ratingError: "Silakan pilih penilaian keseluruhan sebelum mengirim masukan.", anonymousCompany: "Mitra terverifikasi", footerAction: "Bagikan pengalaman Anda",
  },
  hi: {
    eyebrow: "साझेदार प्रतिक्रिया", title: "Al Ghanem Travel के साथ अपना अनुभव साझा करें।", body: "आपकी प्रतिक्रिया हमें यात्रा कंपनियों और उनके अतिथियों की अधिक देखभाल और स्पष्टता के साथ सेवा करने में सहायता देती है।", trust: "हम केवल वास्तविक प्रतिक्रिया प्रकाशित करते हैं, जिसकी हमारी टीम समीक्षा करती है और जिसके प्रकाशन की अनुमति दी गई हो।", approvedTitle: "अनुमोदित साझेदार प्रतिक्रिया", approvedBody: "हर टिप्पणी मॉडरेशन के बाद ही प्रकाशित होती है। कंपनी का नाम केवल उत्तरदाता की अनुमति पर दिखाया जाता है।", approvedEmpty: "स्वीकृत प्रतिक्रिया यहाँ तब दिखाई देगी जब कोई साझेदार उसे सार्वजनिक रूप से साझा करना चुनेगा।", formTitle: "समीक्षा के लिए प्रतिक्रिया भेजें", formBody: "कृपया Al Ghanem Travel के साथ वास्तविक अनुभव के आधार पर प्रतिक्रिया साझा करें। आपकी प्रविष्टि अपने-आप प्रकाशित नहीं होगी।", companyName: "कंपनी का नाम", contactName: "मुख्य संपर्क", email: "व्यावसायिक ईमेल", phone: "टेलीफोन या व्हाट्सऐप", serviceType: "प्राप्त सेवा", servicePlaceholder: "सेवा चुनें या बताएं", rating: "समग्र मूल्यांकन", reviewBody: "आपकी प्रतिक्रिया", reviewPlaceholder: "बताएं कि क्या अच्छा रहा और हम क्या बेहतर कर सकते हैं।", experienceConfirmed: "मैं पुष्टि करता/करती हूँ कि यह प्रतिक्रिया Al Ghanem Travel के साथ वास्तविक अनुभव पर आधारित है।", publishConsent: "मैं Al Ghanem Travel को इस प्रतिक्रिया की संभावित सार्वजनिक प्रकाशन हेतु समीक्षा करने की अनुमति देता/देती हूँ।", displayCompanyName: "यदि प्रतिक्रिया स्वीकृत हो, तो आप मेरी कंपनी का नाम प्रदर्शित कर सकते हैं।", submit: "समीक्षा हेतु भेजें", sending: "प्रतिक्रिया भेजी जा रही है…", success: "धन्यवाद। आपकी प्रतिक्रिया मिल गई है और प्रकाशन से पहले समीक्षा की जाएगी।", error: "आपकी प्रतिक्रिया भेजी नहीं जा सकी। कृपया पुनः प्रयास करें या सीधे Al Ghanem Travel से संपर्क करें।", ratingError: "प्रतिक्रिया भेजने से पहले समग्र मूल्यांकन चुनें।", anonymousCompany: "सत्यापित साझेदार", footerAction: "अपना अनुभव साझा करें",
  },
};
