import type { Locale } from "@/lib/i18n";

export const seoCopy: Record<Locale, { home: { title: string; description: string }; portfolio: { title: string; description: string }; inquiry: { title: string; description: string } }> = {
  en: { home: { title: "Al Ghanem Travel | Islamic Tourism & Travel Services", description: "Multilingual corporate accommodation and religious-travel coordination for Madinah programmes." }, portfolio: { title: "Madinah Hotel Directory | Al Ghanem Travel", description: "Explore Madinah accommodation options for corporate groups and religious-travel programmes, with arrangements confirmed through Al Ghanem Travel." }, inquiry: { title: "Corporate Accommodation Enquiry | Al Ghanem Travel", description: "Submit group, long-stay, or programme accommodation requirements for Madinah and future Makkah services." } },
  ar: { home: { title: "الغانم ترافل | السياحة الإسلامية وخدمات السفر", description: "تنسيق متعدد اللغات لإقامات الشركات وبرامج السفر الديني في المدينة المنورة." }, portfolio: { title: "دليل فنادق المدينة المنورة | الغانم ترافل", description: "استعرض خيارات الإقامة في المدينة المنورة للمجموعات وبرامج السفر الديني، مع تأكيد الترتيبات عبر الغانم ترافل." }, inquiry: { title: "استفسار إقامة للشركات | الغانم ترافل", description: "أرسل متطلبات إقامة المجموعات أو الإقامات الطويلة أو البرامج في المدينة وخدمات مكة المستقبلية." } },
  ms: { home: { title: "Al Ghanem Travel | Pelancongan Islam & Perkhidmatan Perjalanan", description: "Penyelarasan penginapan korporat dan perjalanan ibadah berbilang bahasa untuk program Madinah." }, portfolio: { title: "Direktori Hotel Madinah | Al Ghanem Travel", description: "Terokai pilihan penginapan Madinah untuk kumpulan korporat dan program ibadah, dengan susunan disahkan bersama Al Ghanem Travel." }, inquiry: { title: "Pertanyaan Penginapan Korporat | Al Ghanem Travel", description: "Hantar keperluan penginapan kumpulan, jangka panjang, atau program bagi Madinah dan perkhidmatan Makkah masa hadapan." } },
  ur: { home: { title: "Al Ghanem Travel | اسلامی سیاحت اور سفری خدمات", description: "مدینہ پروگراموں کے لیے کثیر لسانی کارپوریٹ رہائش اور مذہبی سفر کا انتظام۔" }, portfolio: { title: "مدینہ ہوٹل ڈائریکٹری | Al Ghanem Travel", description: "کارپوریٹ گروپس اور مذہبی سفری پروگراموں کے لیے مدینہ کے رہائشی اختیارات دیکھیں، اور انتظامات Al Ghanem Travel کے ذریعے طے کریں۔" }, inquiry: { title: "کارپوریٹ رہائش انکوائری | Al Ghanem Travel", description: "مدینہ اور مستقبل کی مکہ خدمات کے لیے گروپ، طویل قیام، یا پروگرام رہائش کی ضروریات بھیجیں۔" } },
  id: { home: { title: "Al Ghanem Travel | Pariwisata Islam & Layanan Perjalanan", description: "Koordinasi akomodasi korporat dan perjalanan ibadah multibahasa untuk program Madinah." }, portfolio: { title: "Direktori Hotel Madinah | Al Ghanem Travel", description: "Jelajahi pilihan akomodasi Madinah untuk grup korporat dan program ibadah, dengan pengaturan melalui Al Ghanem Travel." }, inquiry: { title: "Pertanyaan Akomodasi Korporat | Al Ghanem Travel", description: "Kirim kebutuhan akomodasi grup, masa tinggal panjang, atau program untuk Madinah dan layanan Makkah mendatang." } },
  hi: { home: { title: "अल घनेम ट्रैवल | इस्लामिक टूरिज्म और ट्रैवल सर्विसेज", description: "मदीना कार्यक्रमों के लिए बहुभाषी कॉर्पोरेट आवास और धार्मिक यात्रा समन्वय।" }, portfolio: { title: "मदीना होटल निर्देशिका | अल घनेम ट्रैवल", description: "कॉर्पोरेट समूहों और धार्मिक यात्रा कार्यक्रमों के लिए मदीना आवास विकल्प देखें, जिनकी व्यवस्था अल घनेम ट्रैवल के माध्यम से की जाती है।" }, inquiry: { title: "कॉर्पोरेट आवास अनुरोध | अल घनेम ट्रैवल", description: "मदीना और भविष्य की मक्का सेवाओं के लिए समूह, दीर्घकालिक या कार्यक्रम आवास आवश्यकताएं भेजें।" } },
};
