export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  externalStorageOrigin: process.env.ASSET_STORAGE_ORIGIN ?? "",
  storageProvider: process.env.STORAGE_PROVIDER ?? "",
  s3Bucket: process.env.S3_BUCKET ?? "",
  s3Region: process.env.S3_REGION ?? "",
  s3Endpoint: process.env.S3_ENDPOINT ?? "",
  s3PublicOrigin: process.env.S3_PUBLIC_ORIGIN ?? process.env.ASSET_STORAGE_ORIGIN ?? "",
  authProvider: process.env.AUTH_PROVIDER ?? "",
  externalMediaManifestPath: process.env.EXTERNAL_MEDIA_MANIFEST_PATH ?? "",
};
