export type MadinahDirectoryZone =
  | "central_north"
  | "central_east"
  | "central_south"
  | "central_west"
  | "northern_transfer"
  | "other_districts";

export type MadinahPlanningHotel = {
  slug: string;
  name: string;
  arabicName: string;
  zone: MadinahDirectoryZone;
  grade: "5-star" | "4-star" | "3-star"   | "serviced-apartments"
  | "unclassified";
  distanceEstimate: string;
  walkingEstimate: string;
  vehicleEstimate?: string;
  accessMode: "walkable" | "transfer_advised";
  routeReview?: "planning" | "live_google";
  planningNote: string;
};

/**
 * Source: user-provided “Madinah Hotels – classified by location and distance from the Haram” planning file, dated 2026.
 * These are planning estimates, not verified inventory or guaranteed route, amenity, grade, or availability statements.
 */
export const madinahPlanningHotels: MadinahPlanningHotel[] = [
  { slug: "dar-al-iman-intercontinental", name: "Dar Al Iman InterContinental", arabicName: "دار الإيمان إنتركونتيننتال", zone: "central_north", grade: "5-star", distanceEstimate: "1.1 km", walkingEstimate: "15 min", accessMode: "walkable", routeReview: "live_google", planningNote: "Live Google Maps walking route checked on 17 August 2026; the original 30–60 m estimate was not retained." },
  { slug: "oberoi-madinah", name: "Oberoi Madinah", arabicName: "أوبروي المدينة", zone: "central_north", grade: "5-star", distanceEstimate: "60–100 m", walkingEstimate: "1–2 min", accessMode: "walkable", planningNote: "Northern courtyard view and women’s entrance note in the supplied planning file." },
  { slug: "pullman-zamzam-madinah", name: "Pullman Zamzam Madina", arabicName: "فندق زمزم بولمان المدينة", zone: "central_south", grade: "5-star", distanceEstimate: "230 m", walkingEstimate: "3 min", accessMode: "walkable", routeReview: "live_google", planningNote: "Live Google Maps walking route checked on 17 August 2026; Accor separately publishes 100 m / 3 min to its selected mosque access point." },
  { slug: "shaza-madinah", name: "Shaza Regency Plaza Al Madinah", arabicName: "فندق شذا ريجنسي بلازا المدينة المنورة", zone: "central_north", grade: "5-star", distanceEstimate: "120–180 m", walkingEstimate: "3–4 min", accessMode: "walkable", planningNote: "Northern central-area planning record." },
  { slug: "anwar-al-madinah-movenpick", name: "Anwar Al Madinah Mövenpick", arabicName: "أنوار المدينة موفنبيك", zone: "central_north", grade: "5-star", distanceEstimate: "900 m", walkingEstimate: "12 min", accessMode: "walkable", routeReview: "live_google", planningNote: "Live Google Maps walking route checked on 17 August 2026; the original 150–250 m / 4–5 min estimate was not retained." },
  { slug: "hilton-madinah", name: "Madinah Hilton", arabicName: "فندق هيلتون المدينة", zone: "central_north", grade: "5-star", distanceEstimate: "300–400 m", walkingEstimate: "7–10 min", accessMode: "walkable", planningNote: "King Fahad Road planning record; current operating name reviewed as Madinah Hilton." },
  { slug: "le-meridien-madinah", name: "Le Méridien Medina", arabicName: "لو ميريديان المدينة", zone: "central_north", grade: "5-star", distanceEstimate: "350–450 m", walkingEstimate: "8–10 min", accessMode: "walkable", planningNote: "King Fahad Road planning record." },
  { slug: "dallah-taibah", name: "Dallah Taibah", arabicName: "دلة طيبة", zone: "central_north", grade: "4-star", distanceEstimate: "400–500 m", walkingEstimate: "10–12 min", accessMode: "walkable", planningNote: "King Fahad Road planning record." },
  { slug: "al-haram-hotel", name: "Dar Al Eiman Al Haram Hotel", arabicName: "فندق دار الإيمان الحرم", zone: "central_north", grade: "4-star", distanceEstimate: "450–550 m", walkingEstimate: "11–13 min", accessMode: "walkable", planningNote: "Northern central-area planning record; current operator identity reviewed as Dar Al Eiman Al Haram Hotel." },
  { slug: "eman-royal", name: "Emaar Royal Hotel", arabicName: "فندق إعمار رويال", zone: "central_north", grade: "4-star", distanceEstimate: "500–600 m", walkingEstimate: "12–15 min", accessMode: "walkable", planningNote: "Northern central-area planning record; current identity reviewed as Emaar Royal Hotel, formerly Al Eiman Royal." },
  { slug: "almasa-grand", name: "Almasa Grand", arabicName: "الماسة جراند", zone: "central_north", grade: "4-star", distanceEstimate: "600–700 m", walkingEstimate: "15–18 min", accessMode: "walkable", planningNote: "King Fahad Road planning record." },
  { slug: "coral-madinah", name: "Rua Al Hijrah Hotel (Coral Al Madinah)", arabicName: "فندق رؤى الهجرة (كورال المدينة)", zone: "central_north", grade: "4-star", distanceEstimate: "650–750 m", walkingEstimate: "16–19 min", accessMode: "walkable", planningNote: "Northern central-area planning record; current operating identity reviewed as Rua Al Hijrah Hotel, formerly Coral Al Madinah." },
  { slug: "golden-tulip-madinah", name: "Golden Tulip Madinah", arabicName: "جولدن توليب المدينة", zone: "central_north", grade: "4-star", distanceEstimate: "700–800 m", walkingEstimate: "18–22 min", accessMode: "walkable", planningNote: "Further within the northern central area according to the planning file." },
  { slug: "ramada-madinah-al-qibla", name: "Al Qibla Hotel", arabicName: "فندق القبلة", zone: "central_north", grade: "4-star", distanceEstimate: "800–1,000 m", walkingEstimate: "20–25 min", accessMode: "walkable", planningNote: "Current identity reviewed as Al Qibla Hotel; legacy Ramada name retained only for search compatibility." },

  { slug: "al-mokhtara-international", name: "Al Mokhtara International", arabicName: "المختارة الدولية", zone: "central_east", grade: "3-star", distanceEstimate: "100–200 m", walkingEstimate: "2–4 min", accessMode: "walkable", planningNote: "Near Al-Baqi Gate according to the supplied planning file." },
  { slug: "al-jawhara-madinah", name: "Al Jawhara Madinah", arabicName: "الجوهرة", zone: "central_east", grade: "3-star", distanceEstimate: "150–250 m", walkingEstimate: "3–5 min", accessMode: "walkable", planningNote: "Behind the eastern side of the Haram in the planning file." },
  { slug: "al-mokhtara-golden", name: "Mokhtara Golden Hotel", arabicName: "فندق المختارة الذهبي", zone: "central_east", grade: "3-star", distanceEstimate: "200–300 m", walkingEstimate: "5–7 min", accessMode: "walkable", planningNote: "Eastern central-area planning record; current operator-preferred identity reviewed as Mokhtara Golden Hotel." },
  { slug: "al-taj-madinah", name: "Al Taj Madinah", arabicName: "التاج", zone: "central_east", grade: "3-star", distanceEstimate: "200–300 m", walkingEstimate: "5–7 min", accessMode: "walkable", planningNote: "Near eastern Bab Al Salam in the supplied planning file." },
  { slug: "al-ansar-madinah", name: "Al Ansar Palace Golden Tulip Hotel", arabicName: "فندق قصر الأنصار جولدن توليب", zone: "central_east", grade: "3-star", distanceEstimate: "250–350 m", walkingEstimate: "6–8 min", accessMode: "walkable", planningNote: "Eastern central-area planning record; exact gallery match reviewed as Al Ansar Palace Golden Tulip Hotel." },
  { slug: "al-nokhba-madinah", name: "Maden Hotel (Al Nokhba Royal Inn)", arabicName: "فندق مادن (النخبة رويال إن)", zone: "central_east", grade: "3-star", distanceEstimate: "300–400 m", walkingEstimate: "8–10 min", accessMode: "walkable", planningNote: "Eastern central-area planning record; current operating identity reviewed as Maden Hotel, formerly Al Nokhba Royal Inn." },
  { slug: "al-durrah-madinah", name: "Durra Al Madinah Hotel", arabicName: "فندق درة المدينة", zone: "central_east", grade: "3-star", distanceEstimate: "350–450 m", walkingEstimate: "9–11 min", accessMode: "walkable", planningNote: "Eastern central-area planning record; current identity reviewed as Durra Al Madinah Hotel." },
  { slug: "al-rehab-madinah", name: "Rehab Taba Hotel (Rehab Harmony)", arabicName: "فندق رحاب طابة (رحاب هارموني)", zone: "central_east", grade: "3-star", distanceEstimate: "400–500 m", walkingEstimate: "10–12 min", accessMode: "walkable", planningNote: "Eastern central-area planning record." },
  { slug: "sidrat-al-madina", name: "Sidrat Al Madina Hotel", arabicName: "فندق سدرة المدينة", zone: "central_north", grade: "unclassified", distanceEstimate: "Not published", walkingEstimate: "Not published", accessMode: "transfer_advised", planningNote: "Identity matched to an independent Medina hotel listing; exact property point and licensed gallery remain pending." },
  { slug: "al-eman-east", name: "Al Eman (East Branch)", arabicName: "الإيمان (فرع شرقي)", zone: "central_east", grade: "3-star", distanceEstimate: "450–550 m", walkingEstimate: "11–13 min", accessMode: "walkable", planningNote: "Eastern/southern planning record." },
  { slug: "al-waleed-madinah", name: "Al Waleed Madinah", arabicName: "الوليد", zone: "central_east", grade: "3-star", distanceEstimate: "500–600 m", walkingEstimate: "13–15 min", accessMode: "walkable", planningNote: "Eastern central-area planning record." },

  { slug: "rawdah-al-aqiq", name: "Rawdah Al Aqiq", arabicName: "الروضة العقيق", zone: "central_south", grade: "4-star", distanceEstimate: "200–300 m", walkingEstimate: "5–8 min", accessMode: "walkable", planningNote: "Southern zone, near Bab Al Salam, in the supplied planning file." },
  { slug: "andalus-palace-madinah", name: "Andalus Palace Madinah", arabicName: "الأندلس بالاس", zone: "central_south", grade: "4-star", distanceEstimate: "300–400 m", walkingEstimate: "8–10 min", accessMode: "walkable", planningNote: "Southern central-area planning record." },
  { slug: "al-andalus-madinah", name: "Al Andalus Madinah", arabicName: "الأندلس", zone: "central_south", grade: "3-star", distanceEstimate: "300–400 m", walkingEstimate: "8–10 min", accessMode: "walkable", planningNote: "Southern central-area planning record." },
  { slug: "al-aqsa-madinah", name: "Al Aqsa Madinah", arabicName: "الأقصى", zone: "central_south", grade: "3-star", distanceEstimate: "400–500 m", walkingEstimate: "10–12 min", accessMode: "walkable", planningNote: "Southern central-area planning record." },
  { slug: "al-shorfa-serviced-apartments", name: "Al Shorfa Serviced Apartments", arabicName: "الشرفة شقق فندقية", zone: "central_south", grade: "serviced-apartments", distanceEstimate: "400–500 m", walkingEstimate: "10–12 min", accessMode: "walkable", planningNote: "Southern central-area planning record." },
  { slug: "al-ferdous-madinah", name: "Al Ferdous Madinah", arabicName: "الفردوس", zone: "central_south", grade: "3-star", distanceEstimate: "500–600 m", walkingEstimate: "12–15 min", accessMode: "walkable", planningNote: "Southern/eastern planning record." },
  { slug: "al-diyafah-serviced-apartments", name: "Al Diyafah Serviced Apartments", arabicName: "الضيافة شقق فندقية", zone: "central_south", grade: "serviced-apartments", distanceEstimate: "500–600 m", walkingEstimate: "12–15 min", accessMode: "walkable", planningNote: "Southern central-area planning record." },

  { slug: "madinah-harmony", name: "Al Madinah Harmony Hotel", arabicName: "فندق المدينة هارموني", zone: "central_west", grade: "4-star", distanceEstimate: "400–500 m", walkingEstimate: "10–12 min", accessMode: "walkable", planningNote: "Western side of the Haram in the supplied planning file; current listing name reviewed as Al Madinah Harmony Hotel." },
  { slug: "sidra-alia-al-dahabi-madinah", name: "Sidra Alia Al-Dahabi Hotel", arabicName: "فندق السدرة العالية الذهبي", zone: "other_districts", grade: "unclassified", distanceEstimate: "Not published", walkingEstimate: "Not published", accessMode: "transfer_advised", planningNote: "Identity and property gallery found in current public hotel listings; exact map point and licensed gallery remain pending." },
  { slug: "taqwa-manazil-madina", name: "Taqwa Manazil Madina", arabicName: "فندق منازل التقوى", zone: "other_districts", grade: "unclassified", distanceEstimate: "Not published", walkingEstimate: "Not published", accessMode: "transfer_advised", planningNote: "Identity matched to a current Medina hotel listing on Omar Bin Al Khattab Road; exact property point and licensed gallery remain pending." },
  { slug: "karam-al-sada-madinah", name: "Karam Al Sada Hotel", arabicName: "فندق كرم السعادة", zone: "other_districts", grade: "unclassified", distanceEstimate: "Not published", walkingEstimate: "Not published", accessMode: "transfer_advised", planningNote: "Identity matched to a current Medina hotel listing in Al Fath; exact property point and licensed gallery remain pending." },
  { slug: "al-aliyah-madinah", name: "Al Aliyah Madinah", arabicName: "العلية", zone: "central_west", grade: "3-star", distanceEstimate: "600–700 m", walkingEstimate: "15–18 min", accessMode: "walkable", planningNote: "Western central-area planning record." },
  { slug: "al-waqf-serviced-apartments", name: "Al Waqf Serviced Apartments", arabicName: "الوقف شقق فندقية", zone: "central_west", grade: "serviced-apartments", distanceEstimate: "600–700 m", walkingEstimate: "15–18 min", accessMode: "walkable", planningNote: "Western central-area planning record." },
  { slug: "al-sultan-madinah", name: "Al Sultan Madinah", arabicName: "السلطان", zone: "central_west", grade: "3-star", distanceEstimate: "700–800 m", walkingEstimate: "18–20 min", accessMode: "walkable", planningNote: "Western central-area planning record." },
  { slug: "al-jazira-madinah", name: "Al Jazira Madinah", arabicName: "الجزيرة", zone: "central_west", grade: "3-star", distanceEstimate: "800–900 m", walkingEstimate: "20–22 min", accessMode: "walkable", planningNote: "Western central-area planning record." },

  { slug: "marriott-madinah", name: "Marriott Madinah", arabicName: "ماريوت المدينة", zone: "northern_transfer", grade: "5-star", distanceEstimate: "2.5 km", walkingEstimate: "35–40 min", vehicleEstimate: "10 min by car", accessMode: "transfer_advised", planningNote: "Transfer noted in the supplied planning file; walking is not recommended for routine access." },
  { slug: "crowne-plaza-madinah", name: "Crowne Plaza Madinah", arabicName: "كراون بلازا المدينة", zone: "northern_transfer", grade: "5-star", distanceEstimate: "2.8 km", walkingEstimate: "40–45 min", vehicleEstimate: "11 min by car", accessMode: "transfer_advised", planningNote: "Transfer noted in the supplied planning file; walking is not recommended for routine access." },
  { slug: "hilton-garden-inn-madinah", name: "Hilton Garden Inn Madinah", arabicName: "هيلتون جاردن إن المدينة", zone: "northern_transfer", grade: "4-star", distanceEstimate: "3.0 km", walkingEstimate: "45–50 min", vehicleEstimate: "12 min by car", accessMode: "transfer_advised", planningNote: "Transfer noted in the supplied planning file; walking is not recommended for routine access." },
  { slug: "al-aqiq-madinah", name: "Al Aqiq Madinah", arabicName: "العقيق المدينة", zone: "northern_transfer", grade: "5-star", distanceEstimate: "3.0 km", walkingEstimate: "45–50 min", vehicleEstimate: "12 min by car", accessMode: "transfer_advised", planningNote: "Transfer noted in the supplied planning file; walking is not recommended for routine access." },
  { slug: "doubletree-by-hilton-madinah", name: "DoubleTree by Hilton Madinah", arabicName: "دبل تري باي هيلتون المدينة", zone: "northern_transfer", grade: "4-star", distanceEstimate: "3.2 km", walkingEstimate: "50–55 min", vehicleEstimate: "13 min by car", accessMode: "transfer_advised", planningNote: "Transfer noted in the supplied planning file; walking is not recommended for routine access." },
  { slug: "radisson-blu-madinah", name: "Radisson Blu Madinah", arabicName: "راديسون بلو المدينة", zone: "northern_transfer", grade: "5-star", distanceEstimate: "3.5 km", walkingEstimate: "50–55 min", vehicleEstimate: "14 min by car", accessMode: "transfer_advised", planningNote: "Transfer noted in the supplied planning file; walking is not recommended for routine access." },
  { slug: "millennium-madinah", name: "Millennium Madinah", arabicName: "ميلينيوم المدينة", zone: "northern_transfer", grade: "5-star", distanceEstimate: "4.0 km", walkingEstimate: "55–60 min", vehicleEstimate: "16 min by car", accessMode: "transfer_advised", planningNote: "Transfer noted in the supplied planning file; walking is not recommended for routine access." },
  { slug: "sheraton-madinah", name: "Sheraton Madinah", arabicName: "شيراتون المدينة", zone: "northern_transfer", grade: "5-star", distanceEstimate: "4.5 km", walkingEstimate: "65–70 min", vehicleEstimate: "18 min by car", accessMode: "transfer_advised", planningNote: "Transfer noted in the supplied planning file; walking is not recommended for routine access." },
  { slug: "four-points-by-sheraton-madinah", name: "Four Points by Sheraton Madinah", arabicName: "فور بوينتس باي شيراتون المدينة", zone: "northern_transfer", grade: "4-star", distanceEstimate: "5.0 km", walkingEstimate: "70–75 min", vehicleEstimate: "20 min by car", accessMode: "transfer_advised", planningNote: "Transfer noted in the supplied planning file; walking is not recommended for routine access." },

  { slug: "quba-hotel-madinah", name: "Quba Hotel Madinah", arabicName: "فندق قباء", zone: "other_districts", grade: "3-star", distanceEstimate: "1.8 km", walkingEstimate: "25–30 min", vehicleEstimate: "7 min by car", accessMode: "transfer_advised", planningNote: "Near Quba Mosque according to the supplied planning file." },
  { slug: "al-waha-hotel-madinah", name: "Hayah Al Waha Hotel", arabicName: "فندق حياة الواحة", zone: "other_districts", grade: "3-star", distanceEstimate: "2.0 km", walkingEstimate: "30–35 min", vehicleEstimate: "8 min by car", accessMode: "transfer_advised", planningNote: "Transport noted as available in the supplied planning file." },
  { slug: "al-aziziyah-hotel-madinah", name: "Al Aziziyah Hotel Madinah", arabicName: "فندق العزيزية", zone: "other_districts", grade: "3-star", distanceEstimate: "1.5 km", walkingEstimate: "20–25 min", vehicleEstimate: "6 min by car", accessMode: "transfer_advised", planningNote: "Near King Fahad Road according to the supplied planning file." },
  { slug: "al-awali-serviced-apartments", name: "Al Awali Serviced Apartments", arabicName: "شقق العوالي", zone: "other_districts", grade: "serviced-apartments", distanceEstimate: "2.5 km", walkingEstimate: "35–40 min", vehicleEstimate: "10 min by car", accessMode: "transfer_advised", planningNote: "Transport noted as available in the supplied planning file." },
  { slug: "al-aqiq-awali-apartments", name: "Al Aqiq Awali Apartments", arabicName: "شقق العقيق العوالي", zone: "other_districts", grade: "serviced-apartments", distanceEstimate: "2.7 km", walkingEstimate: "40–45 min", vehicleEstimate: "11 min by car", accessMode: "transfer_advised", planningNote: "Transport noted as available in the supplied planning file." },
  { slug: "retaj-awali-apartments", name: "Retaj Awali Apartments", arabicName: "شقق ريتاج العوالي", zone: "other_districts", grade: "serviced-apartments", distanceEstimate: "3.0 km", walkingEstimate: "45–50 min", vehicleEstimate: "12 min by car", accessMode: "transfer_advised", planningNote: "Transport noted as available in the supplied planning file." },
];
