import SiteShell from "@/components/SiteShell";
import SeoHead from "@/components/SeoHead";
import HotelSearch from "@/components/HotelSearch";
import { useLocale } from "@/contexts/LocaleContext";
import { hotelProfiles, ownerPublishedProfile } from "@/lib/portfolio";
import { seoCopy } from "@/lib/seoCopy";
import { reviewCopy } from "@/lib/reviewCopy";
import { trpc } from "@/lib/trpc";
import { resolvePublicContacts } from "@/lib/publicSiteSettings";
import { ArrowDownRight, ArrowUpRight, Building2, Globe2, Hotel, Mail, MessageCircle, MessageSquareQuote, Route, Share2, ShieldCheck, Star } from "lucide-react";
import { useMemo } from "react";
import Link from "@/components/LocaleLink";

const heroImage = "/manus-storage/al-ghanem-madinah-hospitality-hero_e26e2975.jpg";
const corporateHospitalityImage = "/manus-storage/al-ghanem-corporate-hospitality_fe51bd5d.jpg";
const patternDetailImage = "/manus-storage/al-ghanem-islamic-pattern-detail_863efd39.jpg";
const madinahDestinationImage = "/manus-storage/madinah-prophets-mosque-card_dc3ae20c.jpg";
const makkahDestinationImage = "/manus-storage/makkah-kaaba-card_7fc0cc43.jpg";

const heroActionContext = {
  en: { prompt: "Choose what you need", catalogueLabel: "Madinah hotel catalogue", catalogueHint: "Browse hotels, photos, and search by name", inquiryLabel: "Corporate accommodation request", inquiryHint: "Send your accommodation requirements" },
  ar: { prompt: "اختاروا المسار المناسب لكم", catalogueLabel: "دليل وكتالوج فنادق المدينة", catalogueHint: "تصفحوا الفنادق والصور وابحثوا باسم الفندق", inquiryLabel: "طلب إقامة للشركات والمجموعات", inquiryHint: "أرسلوا متطلبات الإقامة الخاصة بكم" },
  ms: { prompt: "Pilih perkara yang anda perlukan", catalogueLabel: "Katalog hotel Madinah", catalogueHint: "Lihat hotel, foto dan cari mengikut nama", inquiryLabel: "Permintaan penginapan korporat", inquiryHint: "Hantar keperluan penginapan anda" },
  ur: { prompt: "اپنی ضرورت کا راستہ منتخب کریں", catalogueLabel: "مدینہ ہوٹل گائیڈ اور کیٹلاگ", catalogueHint: "ہوٹل اور تصاویر دیکھیں، نام سے تلاش کریں", inquiryLabel: "کمپنیوں اور گروپس کے لیے رہائش کی درخواست", inquiryHint: "اپنی رہائش کی ضروریات بھیجیں" },
  id: { prompt: "Pilih kebutuhan Anda", catalogueLabel: "Katalog hotel Madinah", catalogueHint: "Jelajahi hotel, foto, dan cari berdasarkan nama", inquiryLabel: "Permintaan akomodasi perusahaan", inquiryHint: "Kirim kebutuhan akomodasi Anda" },
  hi: { prompt: "अपनी आवश्यकता चुनें", catalogueLabel: "मदीना होटल कैटलॉग", catalogueHint: "होटल और तस्वीरें देखें, नाम से खोजें", inquiryLabel: "कॉर्पोरेट आवास अनुरोध", inquiryHint: "अपनी आवास आवश्यकताएँ भेजें" },
} as const;

const quickContactCopy = {
  en: { eyebrow: "Contact Al Ghanem Travel", title: "Direct channels for your accommodation request", body: "Choose the channel that suits your team; our travel desk will continue the conversation with you.", whatsapp: "Official WhatsApp", email: "Email our travel desk", facebook: "Facebook page" },
  ar: { eyebrow: "تواصلوا معنا الآن", title: "قنوات مباشرة لفريق الغانم ترافل", body: "اختاروا القناة المناسبة لفريقكم، وسيتابع معكم مكتب السفر متطلبات الإقامة والاستفسارات.", whatsapp: "واتساب الغانم ترافل الرسمي", email: "البريد الإلكتروني", facebook: "صفحة فيسبوك" },
  ms: { eyebrow: "Hubungi Al Ghanem Travel", title: "Saluran terus untuk permintaan penginapan anda", body: "Pilih saluran yang sesuai untuk pasukan anda dan meja perjalanan kami akan meneruskan perbualan bersama anda.", whatsapp: "WhatsApp rasmi", email: "E-mel meja perjalanan", facebook: "Halaman Facebook" },
  ur: { eyebrow: "الغانم ٹریول سے رابطہ کریں", title: "آپ کی رہائش کی درخواست کے لیے براہِ راست ذرائع", body: "اپنی ٹیم کے لیے موزوں ذریعہ منتخب کریں؛ ہمارا ٹریول ڈیسک آپ کے ساتھ گفتگو آگے بڑھائے گا۔", whatsapp: "آفیشل واٹس ایپ", email: "ٹریول ڈیسک ای میل", facebook: "فیس بک صفحہ" },
  id: { eyebrow: "Hubungi Al Ghanem Travel", title: "Kanal langsung untuk kebutuhan akomodasi Anda", body: "Pilih kanal yang sesuai untuk tim Anda dan tim perjalanan kami akan melanjutkan percakapan bersama Anda.", whatsapp: "WhatsApp resmi", email: "Email meja perjalanan", facebook: "Halaman Facebook" },
  hi: { eyebrow: "Al Ghanem Travel से संपर्क करें", title: "आपके आवास अनुरोध के लिए सीधे माध्यम", body: "अपनी टीम के लिए उपयुक्त माध्यम चुनें; हमारी यात्रा टीम आपकी बातचीत आगे बढ़ाएगी।", whatsapp: "आधिकारिक WhatsApp", email: "यात्रा डेस्क ईमेल", facebook: "Facebook पेज" },
} as const;

function HeroQuickContact({ copy, contacts }: { copy: (typeof quickContactCopy)[keyof typeof quickContactCopy]; contacts: ReturnType<typeof resolvePublicContacts> }) {
  return <aside aria-label={copy.eyebrow} className="mt-7 max-w-3xl rounded-[1.5rem] border border-[#efcf82]/45 bg-white/10 p-4 shadow-[0_12px_32px_rgba(0,0,0,.14)] backdrop-blur-sm md:p-5"><div className="flex flex-col gap-1"><p className="text-[11px] font-extrabold uppercase tracking-[.14em] text-[#efcf82]">{copy.eyebrow}</p><h2 className="font-serif text-xl leading-tight text-white md:text-2xl">{copy.title}</h2><p className="text-sm leading-6 text-white/75">{copy.body}</p></div><div className="mt-4 grid gap-2 sm:grid-cols-3"><a href={contacts.primaryWhatsAppUrl} target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-[#dfc27f] px-3 py-3 text-center text-xs font-extrabold text-[#153a31] transition hover:bg-white focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[#dfc27f]/45"><MessageCircle size={17} aria-hidden="true" />{copy.whatsapp}</a><a href={contacts.corporateEmailHref} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border border-white/35 bg-white/8 px-3 py-3 text-center text-xs font-bold text-white transition hover:bg-white hover:text-[#153a31] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-white/35"><Mail size={17} aria-hidden="true" />{contacts.email}</a><a href={contacts.facebookUrl} target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border border-white/35 bg-white/8 px-3 py-3 text-center text-xs font-bold text-white transition hover:bg-white hover:text-[#153a31] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-white/35"><Share2 size={17} aria-hidden="true" />{copy.facebook}</a></div></aside>;
}

export default function Home() {
  const { t, locale } = useLocale();
  const managedRecords = trpc.catalogue.published.useQuery();
  const approvedReviews = trpc.reviews.approved.useQuery();
  const siteSettings = trpc.siteSettings.get.useQuery();
  const reviewText = reviewCopy[locale];
  const searchableHotels = useMemo(() => {
    const merged = new Map(hotelProfiles.map(hotel => [hotel.slug, hotel]));
    managedRecords.data?.map(ownerPublishedProfile).filter((hotel): hotel is NonNullable<typeof hotel> => Boolean(hotel)).forEach(hotel => merged.set(hotel.slug, hotel));
    return Array.from(merged.values());
  }, [managedRecords.data]);
  const trustPoints = [[Globe2, t.trust.language], [Building2, t.trust.portfolio], [MessageCircle, t.trust.support]] as const;
  const trustStatement = { en: "17 years of experience · Dedicated travel service", ar: "17 عاماً من الخبرة · خدمة سفر متخصصة", ms: "17 tahun pengalaman · Perkhidmatan perjalanan khusus", ur: "17 سال کا تجربہ · خصوصی سفری خدمت", id: "17 tahun pengalaman · Layanan perjalanan khusus", hi: "17 वर्षों का अनुभव · समर्पित यात्रा सेवा" }[locale];
  const heroActions = heroActionContext[locale];
  const quickContact = quickContactCopy[locale];
  const contacts = resolvePublicContacts(siteSettings.data);
  const managedEnglishDefault = locale === "en" ? siteSettings.data : undefined;
  const standardIcons = [ShieldCheck, Route, Globe2];

  return (
    <SiteShell>
      <SeoHead title={managedEnglishDefault?.defaultSeoTitle || seoCopy[locale].home.title} description={managedEnglishDefault?.defaultSeoDescription || seoCopy[locale].home.description} />
      <section className="relative isolate overflow-hidden bg-[#153a31] text-white">
        <img src={heroImage} alt="" aria-hidden="true" className="absolute inset-0 h-full w-full object-cover opacity-60" />
        <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(15,50,42,.98)_0%,rgba(15,50,42,.86)_42%,rgba(15,50,42,.36)_100%)]" />
        <div className="hero-pattern absolute inset-0 opacity-35" />
        <div aria-label={quickContact.eyebrow} className="absolute inset-x-4 top-4 z-20 grid grid-cols-3 gap-2 rounded-2xl border border-[#efcf82]/35 bg-[#153a31]/75 p-2 shadow-lg backdrop-blur-sm md:hidden"><a href={contacts.primaryWhatsAppUrl} target="_blank" rel="noreferrer" aria-label={quickContact.whatsapp} className="inline-flex min-h-10 items-center justify-center gap-1 rounded-xl bg-[#dfc27f] px-2 text-[11px] font-extrabold text-[#153a31] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white"><MessageCircle size={15} aria-hidden="true" />WhatsApp</a><a href={contacts.corporateEmailHref} aria-label={quickContact.email} className="inline-flex min-h-10 items-center justify-center gap-1 rounded-xl bg-white/10 px-2 text-[11px] font-bold text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white"><Mail size={15} aria-hidden="true" />Email</a><a href={contacts.facebookUrl} target="_blank" rel="noreferrer" aria-label={quickContact.facebook} className="inline-flex min-h-10 items-center justify-center gap-1 rounded-xl bg-white/10 px-2 text-[11px] font-bold text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white"><Share2 size={15} aria-hidden="true" />Facebook</a></div>
        <div className="relative mx-auto grid min-h-[650px] max-w-[1440px] items-end px-5 pb-16 pt-20 md:px-8 md:pb-20 lg:min-h-[700px]">
          <div className="max-w-3xl"><p className="eyebrow text-[#efcf82]">{managedEnglishDefault?.homepageWelcomeEyebrow || t.hero.eyebrow}</p><div className="mt-5 gold-rule bg-[#dfc27f]" /><h1 className="mt-6 font-serif text-5xl leading-[1.02] tracking-[-.035em] text-white md:text-6xl lg:text-7xl">{managedEnglishDefault?.homepageWelcomeTitle || <>{t.hero.title} <span className="text-[#efcf82]">{t.hero.highlight}</span></>}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/78 md:text-xl">{managedEnglishDefault?.homepageWelcomeBody || t.hero.body}</p><HeroQuickContact copy={quickContact} contacts={contacts} /><HotelSearch hotels={searchableHotels} /><p className="mt-8 text-sm font-bold text-[#efcf82]">{heroActions.prompt}</p><div className="mt-3 grid gap-3 sm:grid-cols-2"><Link href="/hotels" className="group inline-flex min-h-[112px] items-center justify-between gap-4 rounded-[1.5rem] bg-[#dfc27f] px-6 py-5 text-[#153a31] shadow-[0_10px_30px_rgba(223,194,127,.22)] transition hover:-translate-y-0.5 hover:bg-white focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[#dfc27f]/45"><span className="min-w-0"><span className="flex items-center gap-2 text-sm font-extrabold leading-5 text-[#503b16]"><Hotel size={18} aria-hidden="true" />{heroActions.catalogueLabel}</span><span className="mt-2 block text-xs font-bold leading-5 text-[#735c2b]">{t.hero.secondary}</span><span className="mt-1 block text-xs font-medium leading-5 text-[#4f4124]">{heroActions.catalogueHint}</span></span><ArrowDownRight size={22} className="shrink-0 transition group-hover:translate-y-0.5" aria-hidden="true" /></Link><Link href="/inquiry" className="group inline-flex min-h-[112px] items-center justify-between gap-4 rounded-[1.5rem] border border-white/45 bg-[#153a31]/15 px-6 py-5 text-white transition hover:-translate-y-0.5 hover:bg-white hover:text-[#153a31] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-white/35"><span className="min-w-0"><span className="flex items-center gap-2 text-sm font-extrabold leading-5 text-white"><Building2 size={18} aria-hidden="true" />{heroActions.inquiryLabel}</span><span className="mt-2 block text-xs font-bold leading-5 text-[#efcf82] group-hover:text-[#7d5b20]">{t.hero.primary}</span><span className="mt-1 block text-xs font-medium leading-5 text-white/70 group-hover:text-[#496a61]">{heroActions.inquiryHint}</span></span><ArrowUpRight size={22} className="shrink-0 transition group-hover:-translate-y-0.5" aria-hidden="true" /></Link></div></div>
          <p className="mt-12 text-[11px] font-bold uppercase tracking-[.15em] text-white/55">{t.hero.note}</p>
        </div>
      </section>

      <section aria-labelledby="destination-cards" className="border-y border-[#173e35]/10 bg-[#f3eee1]"><div className="mx-auto grid max-w-[1440px] gap-12 px-5 py-20 md:px-8 lg:grid-cols-[.78fr_1.22fr] lg:py-28"><div><p className="eyebrow">{t.city.label}</p><div className="mt-4 gold-rule" /><h2 id="destination-cards" className="section-title max-w-lg">{t.city.title}</h2><p className="mt-6 max-w-lg text-[15px] leading-7 text-[#557068]">{t.city.body}</p><Link href="/hotels" className="mt-8 inline-flex items-center gap-3 text-xs font-bold uppercase tracking-[.12em] text-[#173e35] transition hover:text-[#a9853d]">{t.city.action}<ArrowUpRight size={16} /></Link></div><div className="grid gap-4 sm:grid-cols-2"><Link href="/hotels" aria-label={t.city.action} className="group relative block overflow-hidden rounded-[1.5rem] bg-[#153a31] p-7 text-white transition duration-200 hover:-translate-y-1 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[#dfc27f]/60 sm:min-h-[300px]"><img src={madinahDestinationImage} alt="" aria-hidden="true" className="absolute inset-0 h-full w-full object-cover transition duration-500 group-hover:scale-105" /><div className="absolute inset-0 bg-[linear-gradient(135deg,rgba(12,53,43,.93)_0%,rgba(12,53,43,.68)_48%,rgba(12,53,43,.2)_100%)]" /><div className="absolute -right-10 -top-10 h-44 w-44 rounded-full border border-[#dfc27f]/40 transition-transform duration-300 group-hover:scale-110" /><div className="absolute -right-3 -top-3 h-28 w-28 rounded-full border border-[#dfc27f]/30 transition-transform duration-300 group-hover:scale-110" /><p className="relative z-10 text-[10px] font-bold tracking-[.17em] text-[#efcf82]">{t.city.active}</p><p className="relative z-10 mt-24 font-serif text-3xl leading-tight">{t.city.madinah}</p><p className="relative z-10 mt-4 text-sm text-white/80">{t.city.madinahDetail}</p></Link><article className="relative overflow-hidden rounded-[1.5rem] border border-[#a9853d]/35 bg-[#151510] p-7 text-white sm:min-h-[300px]"><img src={makkahDestinationImage} alt="" aria-hidden="true" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-[linear-gradient(135deg,rgba(20,19,14,.87)_0%,rgba(20,19,14,.54)_58%,rgba(113,78,25,.18)_100%)]" /><div className="absolute -right-12 -bottom-12 h-48 w-48 rotate-45 border border-[#dfc27f]/35" /><p className="relative z-10 text-[10px] font-bold tracking-[.17em] text-[#efcf82]">{t.city.comingSoon}</p><p className="relative z-10 mt-24 font-serif text-3xl leading-tight">{t.city.makkah}</p><p className="relative z-10 mt-4 text-sm text-white/80">{t.city.makkahDetail}</p></article></div></div></section>

      <section className="mx-auto grid max-w-[1440px] overflow-hidden border-y border-[#173e35]/10 bg-[#f4f0e6] md:grid-cols-4">{[...trustPoints, [ShieldCheck, trustStatement] as const].map(([Icon, label], index) => <div className={`flex items-center gap-4 px-5 py-6 md:px-6 ${index ? "md:border-s md:border-[#173e35]/10" : ""}`} key={label}><span className="grid h-9 w-9 place-items-center rounded-full bg-white text-[#a9853d]"><Icon size={17} /></span><p className="text-sm font-semibold text-[#31584d]">{label}</p></div>)}</section>

      <section id="reviews" className="border-b border-[#173e35]/10 bg-white"><div className="mx-auto max-w-[1440px] px-5 py-16 md:px-8 lg:py-20"><div className="flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div className="max-w-2xl"><p className="eyebrow">{reviewText.eyebrow}</p><div className="mt-4 gold-rule" /><h2 className="section-title mt-5">{reviewText.approvedTitle}</h2><p className="mt-5 text-[15px] leading-7 text-[#557068]">{reviewText.approvedBody}</p></div><Link href="/reviews#share" className="inline-flex shrink-0 items-center gap-3 self-start rounded-full border border-[#173e35]/20 px-5 py-3 text-xs font-bold uppercase tracking-[.1em] text-[#173e35] transition hover:border-[#a9853d] hover:text-[#a9853d] lg:self-auto">{reviewText.footerAction}<ArrowUpRight size={16} /></Link></div><div className="mt-10 grid gap-4 lg:grid-cols-3">{approvedReviews.isLoading ? Array.from({ length: 3 }, (_, index) => <div key={index} className="h-52 animate-pulse rounded-[1.5rem] bg-[#f4f0e6]" />) : approvedReviews.data?.length ? approvedReviews.data.slice(0, 3).map(review => <article key={review.id} className="rounded-[1.5rem] border border-[#173e35]/10 bg-[#fbfaf6] p-6 shadow-[0_10px_30px_rgba(23,62,53,.04)]"><div className="flex items-center gap-1 text-[#a9853d]" aria-label={`${review.rating} of 5`}><span className="sr-only">{review.rating}/5</span>{Array.from({ length: 5 }, (_, index) => <Star key={index} size={15} fill={index < review.rating ? "currentColor" : "none"} className={index < review.rating ? "" : "text-[#d7dfda]"} />)}</div><p className="mt-4 text-sm leading-7 text-[#496a61]">“{review.reviewBody}”</p><p className="mt-5 text-xs font-bold uppercase tracking-[.1em] text-[#173e35]">{review.companyName ?? reviewText.anonymousCompany}</p>{review.serviceType && <p className="mt-1 text-xs text-[#71857f]">{review.serviceType}</p>}</article>) : <Link href="/reviews#share" aria-label={reviewText.footerAction} className="group lg:col-span-3 flex flex-col items-start gap-4 rounded-[1.5rem] border border-dashed border-[#a9853d]/60 bg-[#f8f5ed] p-7 text-sm leading-7 text-[#58726a] transition hover:border-[#a9853d] hover:bg-[#fffdf8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#a9853d]"><span className="inline-flex items-center gap-3 rounded-full bg-[#fff8e8] px-4 py-2 text-xs font-bold uppercase tracking-[.1em] text-[#8d6a27]"><Star size={16} fill="currentColor" /><MessageSquareQuote size={16} />{reviewText.footerAction}</span><p>{reviewText.approvedEmpty}</p><span className="inline-flex items-center gap-2 font-bold text-[#173e35] transition group-hover:text-[#a9853d]">{reviewText.footerAction}<ArrowUpRight size={15} /></span></Link>}</div></div></section>

      <section id="approach" className="mx-auto grid max-w-[1440px] gap-12 px-5 py-20 md:px-8 lg:grid-cols-[.82fr_1.18fr] lg:py-28"><div className="lg:sticky lg:top-32 lg:self-start"><p className="eyebrow">{t.standards.eyebrow}</p><div className="mt-4 gold-rule" /><h2 className="section-title max-w-lg">{t.standards.title}</h2><p className="mt-6 max-w-md text-[15px] leading-7 text-[#557068]">{t.standards.body}</p><div className="mt-8 overflow-hidden rounded-[1.5rem] border border-[#173e35]/10"><img src={corporateHospitalityImage} alt="" aria-hidden="true" className="aspect-[3/2] w-full object-cover" /></div></div><div className="grid gap-px overflow-hidden rounded-[1.5rem] border border-[#173e35]/10 bg-[#173e35]/10 md:grid-cols-3">{t.standards.items.map((item, index) => { const Icon = standardIcons[index] ?? ShieldCheck; return <article className="min-h-[280px] bg-[#fbfaf6] p-7 transition hover:bg-white" key={item.title}><span className="grid h-11 w-11 place-items-center rounded-full border border-[#c49b4d]/40 text-[#a9853d]"><Icon size={20} /></span><p className="mt-8 font-serif text-2xl text-[#173e35]">{item.title}</p><p className="mt-4 text-sm leading-6 text-[#59726b]">{item.body}</p></article>; })}</div></section>

      <section className="mx-auto grid max-w-[1440px] gap-10 px-5 py-20 md:px-8 lg:grid-cols-[1fr_260px] lg:items-end lg:py-28"><div><div className="max-w-2xl"><p className="eyebrow">{t.process.eyebrow}</p><div className="mt-4 gold-rule" /><h2 className="section-title">{t.process.title}</h2><p className="mt-5 text-[15px] leading-7 text-[#557068]">{t.process.body}</p></div><div className="mt-12 grid gap-6 md:grid-cols-3">{t.process.steps.map(step => <article className="border-t-2 border-[#c49b4d] pt-5" key={step.number}><p className="text-xs font-bold tracking-[.14em] text-[#a9853d]">{step.number}</p><h3 className="mt-5 font-serif text-2xl text-[#173e35]">{step.title}</h3><p className="mt-4 text-sm leading-6 text-[#5c746d]">{step.body}</p></article>)}</div></div><img src={patternDetailImage} alt="" aria-hidden="true" className="mx-auto hidden w-full max-w-[260px] rounded-[1.5rem] border border-[#173e35]/10 object-cover lg:block" /></section>

      <section className="mx-auto mb-20 max-w-[1380px] overflow-hidden rounded-[2rem] bg-[#153a31] px-6 py-14 text-white md:mb-24 md:px-12 lg:px-16"><div className="relative grid gap-8 lg:grid-cols-[1fr_auto] lg:items-end"><div className="absolute -right-32 -top-32 h-80 w-80 rounded-full border border-[#dfc27f]/25" /><div className="relative max-w-3xl"><p className="eyebrow text-[#efcf82]">AL GHANEM TRAVEL</p><h2 className="mt-4 font-serif text-4xl leading-tight md:text-5xl">{t.cta.title}</h2><p className="mt-5 max-w-2xl text-base leading-7 text-white/70">{t.cta.body}</p></div><div className="relative"><Link href="/inquiry" className="rounded-full bg-[#dfc27f] px-6 py-4 text-center text-xs font-bold uppercase tracking-[.1em] text-[#153a31] transition hover:bg-white">{t.cta.action}</Link></div></div></section>
    </SiteShell>
  );
}
